export const EVENTS = [
  {
    id: 'hackathon',
    title: 'Hackathon',
    emoji: '⚡',
    category: 'Coding',
    tagColor: 'bg-blue-500',
    description: 'A 24-hour coding marathon where teams build innovative solutions to real-world problems. Pitch your prototype to industry experts and claim the championship.',
    date: 'October 24, 2026',
    time: '10:00 AM – 10:00 AM (Next Day)',
    venue: 'Main Auditorium, Block A',
    teamSize: '2 – 4 Members',
    eligibility: 'Open to all B.Tech / BCA students',
    fee: '₹200 per team',
    prize: '₹50,000 Prize Pool',
    rules: [
      'All code must be written during the event — no pre-built projects.',
      'Open-source libraries and APIs are permitted.',
      'Teams must present a working prototype at the end.',
      'Plagiarism or use of pre-existing repos leads to disqualification.',
      'Team size: 2 to 4 members.',
    ],
    timeline: [
      { time: '10:00 AM', label: 'Registration & Team Formation' },
      { time: '11:00 AM', label: 'Problem Statement Released' },
      { time: '12:00 PM', label: 'Hacking Begins' },
      { time: '08:00 PM', label: 'Mid-Evaluation Checkpoint' },
      { time: '10:00 AM+', label: 'Final Submission Deadline' },
      { time: '12:00 PM+', label: 'Presentations & Prize Distribution' },
    ],
    day: 1,
  },
  {
    id: 'treasure-hunt',
    title: 'Treasure Hunt',
    emoji: '🗺️',
    category: 'Adventure',
    tagColor: 'bg-amber-500',
    description: 'Decode cryptic clues scattered across campus, solve technical puzzles, and race against rival teams to find the final treasure before anyone else.',
    date: 'October 24, 2026',
    time: '11:00 AM – 4:00 PM',
    venue: 'Campus-wide, GEHU',
    teamSize: '3 – 5 Members',
    eligibility: 'Open to all GEHU students',
    fee: '₹100 per team',
    prize: '₹20,000 Prize Pool',
    rules: [
      'Each clue location must be reached in sequence.',
      'No external help (internet search, outsiders) allowed.',
      'Clues may include coding challenges, riddles, and physical tasks.',
      'Destroying or hiding clues for other teams leads to elimination.',
      "Judges' decisions are final.",
    ],
    timeline: [
      { time: '11:00 AM', label: 'Rules Briefing & Clue 1 Released' },
      { time: '11:30 AM', label: 'Hunt Begins' },
      { time: '02:00 PM', label: 'Final Zone Unlocks' },
      { time: '04:00 PM', label: 'Treasure Claimed & Results' },
    ],
    day: 1,
  },
  {
    id: 'esports',
    title: 'E-Sports Arena',
    emoji: '🎮',
    category: 'Gaming',
    tagColor: 'bg-green-500',
    description: 'Gaming tournament featuring Valorant, BGMI, and FIFA. Form your squad, sharpen your aim, and compete for ultimate gaming glory on the big screen.',
    date: 'October 26, 2026',
    time: '10:00 AM – 8:00 PM',
    venue: 'Gaming Arena, Student Center',
    teamSize: '1 – 5 Members (varies by game)',
    eligibility: 'Open to all college students',
    fee: '₹150 per team',
    prize: '₹40,000 Prize Pool',
    rules: [
      'Participants must bring their own peripherals (mouse, keyboard, headset).',
      'No cheats, hacks, or third-party software allowed.',
      'Misconduct results in immediate disqualification.',
      'Referee and observer decisions are final.',
      'Match schedule will be shared 30 minutes before start.',
    ],
    timeline: [
      { time: '10:00 AM', label: 'Valorant Qualifiers' },
      { time: '01:00 PM', label: 'BGMI Qualifiers' },
      { time: '04:00 PM', label: 'FIFA Tournament' },
      { time: '06:00 PM', label: 'Semi-Finals (All Games)' },
      { time: '07:30 PM', label: 'Grand Finals & Ceremony' },
    ],
    day: 3,
  },
  {
    id: 'ctf',
    title: 'Capture The Flag',
    emoji: '🚩',
    category: 'Security',
    tagColor: 'bg-red-500',
    description: 'Test your cybersecurity skills across web exploitation, reverse engineering, cryptography, and forensics. Capture flags, earn points, conquer the leaderboard.',
    date: 'October 25, 2026',
    time: '9:00 AM – 3:00 PM',
    venue: 'Computer Lab 2, Block B',
    teamSize: '1 – 3 Members',
    eligibility: 'Open to all students with basic cybersecurity knowledge',
    fee: '₹100 per team',
    prize: '₹25,000 Prize Pool',
    rules: [
      'Attack-only mode — no attacking infrastructure or other participants.',
      'Flag format will be announced at the start.',
      'Sharing flags or solutions results in disqualification.',
      'Internet access permitted for research only.',
      'All activities are logged; unsportsmanlike conduct = ban.',
    ],
    timeline: [
      { time: '09:00 AM', label: 'Platform Opens & Briefing' },
      { time: '09:30 AM', label: 'CTF Begins' },
      { time: '12:00 PM', label: 'Midpoint Leaderboard Announcement' },
      { time: '03:00 PM', label: 'Platform Closes & Results' },
    ],
    day: 2,
  },
  {
    id: 'workshop',
    title: 'Workshop Series',
    emoji: '🛠️',
    category: 'Learning',
    tagColor: 'bg-purple-500',
    description: 'Hands-on sessions covering AI/ML, Full-Stack Development, and UI/UX Design. Led by industry professionals. Gain real skills with a participation certificate.',
    date: 'October 24–25, 2026',
    time: '9:00 AM – 1:00 PM (Both Days)',
    venue: 'Seminar Hall, Block D',
    teamSize: 'Individual',
    eligibility: 'Open to all — no prerequisites for most sessions',
    fee: '₹50 per session',
    prize: 'Certificate + Industry Mentorship',
    rules: [
      'Bring your own laptop with required software pre-installed.',
      'Prerequisites per session listed on registration form.',
      'Attendance mandatory for certificate.',
      'Recording prohibited without prior permission.',
      'Q&A strictly in designated time slots.',
    ],
    timeline: [
      { time: '09:00 AM', label: 'Day 1: AI/ML Fundamentals (Hands-on)' },
      { time: '09:00 AM', label: 'Day 2: Full-Stack in 3 Hours' },
      { time: '11:00 AM', label: 'UI/UX Design Sprint' },
      { time: '01:00 PM', label: 'Certificate Distribution' },
    ],
    day: 1,
  },
];

export const SCHEDULE = [
  // Day 1
  { id: 's1', day: 1, time: '09:00', label: 'Registration & Check-in', track: 'General', venue: 'Main Gate' },
  { id: 's2', day: 1, time: '10:00', label: 'Opening Ceremony & Keynote', track: 'General', venue: 'Main Auditorium' },
  { id: 's3', day: 1, time: '11:00', label: 'Hackathon Kick-off', track: 'Coding', venue: 'Block A' },
  { id: 's4', day: 1, time: '11:00', label: 'Treasure Hunt Begins', track: 'Adventure', venue: 'Campus-wide' },
  { id: 's5', day: 1, time: '09:00', label: 'Workshop: AI/ML Fundamentals', track: 'Learning', venue: 'Block D' },
  { id: 's6', day: 1, time: '13:00', label: 'Lunch Break', track: 'General', venue: 'Cafeteria' },
  { id: 's7', day: 1, time: '14:00', label: 'Speaker: Prof. Rajiv Sharma on Future of Tech', track: 'General', venue: 'Auditorium' },
  { id: 's8', day: 1, time: '16:00', label: 'Treasure Hunt Finals & Results', track: 'Adventure', venue: 'Main Ground' },
  { id: 's9', day: 1, time: '20:00', label: 'Hackathon Mid-Eval', track: 'Coding', venue: 'Block A' },
  // Day 2
  { id: 's10', day: 2, time: '09:00', label: 'CTF Platform Opens', track: 'Security', venue: 'Block B' },
  { id: 's11', day: 2, time: '09:00', label: 'Workshop: Full-Stack in 3 Hours', track: 'Learning', venue: 'Block D' },
  { id: 's12', day: 2, time: '10:00', label: 'Hackathon Final Submissions', track: 'Coding', venue: 'Block A' },
  { id: 's14', day: 2, time: '12:00', label: 'CTF Midpoint Leaderboard', track: 'Security', venue: 'Block B' },
  { id: 's15', day: 2, time: '13:00', label: 'Lunch & Networking', track: 'General', venue: 'Cafeteria' },
  { id: 's16', day: 2, time: '14:00', label: 'Hackathon Presentations', track: 'Coding', venue: 'Auditorium' },
  { id: 's17', day: 2, time: '15:00', label: 'CTF Platform Closes & Results', track: 'Security', venue: 'Block B' },
  // Day 3
  { id: 's13', day: 3, time: '10:00', label: 'E-Sports: Valorant Qualifiers', track: 'Gaming', venue: 'Student Center' },
  { id: 's13b', day: 3, time: '13:00', label: 'E-Sports: BGMI Qualifiers', track: 'Gaming', venue: 'Student Center' },
  { id: 's13c', day: 3, time: '15:00', label: 'Lunch Break', track: 'General', venue: 'Cafeteria' },
  { id: 's18', day: 3, time: '19:30', label: 'E-Sports Grand Finals', track: 'Gaming', venue: 'Student Center' },
  // Day 4
  { id: 's19', day: 4, time: '10:00', label: 'Speaker: Ananya Mehta on Scalability', track: 'General', venue: 'Auditorium' },
  { id: 's20', day: 4, time: '12:00', label: 'Speaker: Priya Nair on Design', track: 'General', venue: 'Auditorium' },
  { id: 's21', day: 4, time: '14:00', label: 'Closing Ceremony & Prize Distribution', track: 'General', venue: 'Main Auditorium' },
];

export const SPEAKERS = [
  {
    id: 'sp1',
    name: 'Prof. Rajiv Sharma',
    role: 'Dean of Engineering',
    org: 'Graphic Era Hill University',
    bio: 'Pioneer in embedded systems and IoT research with 20+ years of experience. Author of 3 textbooks and 40+ research papers. Keynote speaker at IEEE conferences globally.',
    initials: 'RS',
    color: '#FFCC00',
  },
  {
    id: 'sp2',
    name: 'Ananya Mehta',
    role: 'Senior Software Engineer',
    org: 'Google India',
    bio: 'Full-stack engineer specializing in distributed systems and developer tools. Open-source contributor with 2000+ GitHub stars. Mentor at multiple national hackathons.',
    initials: 'AM',
    color: '#E63B2E',
  },
  {
    id: 'sp3',
    name: 'Karan Vohra',
    role: 'Cybersecurity Researcher',
    org: 'DRDO / IIT Delhi (Alum)',
    bio: 'National CTF champion and published researcher in network security. Currently working on AI-driven threat detection for critical infrastructure. Regular speaker at null Meets.',
    initials: 'KV',
    color: '#0055FF',
  },
  {
    id: 'sp4',
    name: 'Priya Nair',
    role: 'Product Designer',
    org: 'Figma (Bangalore Office)',
    bio: 'UX designer who led redesigns for 3 top-10 Indian apps. Passionate about accessible design and design systems. Runs a popular YouTube channel on UX with 80K subscribers.',
    initials: 'PN',
    color: '#9B59B6',
  },
];


export const GALLERY_PHOTOS = [
  { id: 'g1', src: 'assets/gallery/photo1.jpg', caption: 'Student playing a mobile battle royale game', category: 'E-Sports' },
  { id: 'g2', src: 'assets/gallery/photo2.jpg', caption: 'Team of three discussing strategy in front of a laptop', category: 'Hackathon' },
  { id: 'g3', src: 'assets/gallery/photo3.jpg', caption: 'Smartphone with earphones ready for a mobile gaming match', category: 'E-Sports' },
  { id: 'g4', src: 'assets/gallery/photo4.jpg', caption: 'Instructor interacting with students working on laptops', category: 'Workshop' },
  { id: 'g5', src: 'assets/gallery/photo5.jpg', caption: 'Group of students closely watching a gaming session on a laptop', category: 'E-Sports' },
];
